# Generated by Django 4.1.7 on 2023-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_emp_tbl_delete_employee_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.IntegerField()),
            ],
        ),
    ]
