# Generated by Django 4.1.7 on 2023-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_emp_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='emp_check',
        ),
        migrations.DeleteModel(
            name='emp_tbl',
        ),
    ]
