# Generated by Django 4.1.7 on 2023-03-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_post_delete_emp_check_delete_emp_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('email', models.TextField()),
                ('empCode', models.TextField()),
                ('dept', models.TextField()),
                ('designation', models.TextField()),
                ('grade', models.TextField()),
                ('isApproved', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
